name: XGo Docker

on:
  push:
    branches: [ master ]
    paths:
      - 'ci/xgo/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: docker build -t image ci/xgo

    - name: Publish
      run: |
        docker tag image docker.pkg.github.com/pangbox/pangfiles/xgo:${GITHUB_SHA}
        docker push docker.pkg.github.com/pangbox/pangfiles/xgo:${GITHUB_SHA}
        docker tag image docker.pkg.github.com/pangbox/pangfiles/xgo:latest
        docker push docker.pkg.github.com/pangbox/pangfiles/xgo:latest
